version: "3.7"

services:
  mono:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "1.1.9-3.3-bullseye"
        NODE_VERSION: "lts/hydrogen"
    volumes:
      - ..:/leviathan:cached
    command: sleep infinity
    #network_mode: service:db
    depends_on:
      - postgres
      - redis
    environment:
      PHAMILY_POSTGRES_HOST: "postgres"
      PHAMILY_POSTGRES_PORT: "5432"
      REDIS_URL: "redis://redis:6379/1"

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7-alpine
    restart: unless-stopped

volumes:
  postgres-data:
